---
# tasks file for nodejs

#- name: Installing node and npm
#  yum:
#    #name: "{{ item }}"
#    name: nodejs,npm
#    #enablerepo: epel
#    state: installed
#  #with_items: nodejs,npm

- name: Installing nvm
  shell: 'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash'

- name: Executing nvm
  command: /home/ec2-user/.nvm/nvm.sh

- name: Installing node and npm
  command: nvm install node
