---
# tasks file for nodejs

#- name: Installing node and npm
#  yum:
#    #name: "{{ item }}"
#    name: nodejs,npm
#    #enablerepo: epel
#    state: installed
#  #with_items: nodejs,npm

- name: Installing node and npm
  command: nvm install node
