---
# tasks file for nodejs

#- name: Installing node and npm
#  yum:
#    #name: "{{ item }}"
#    name: nodejs,npm
#    #enablerepo: epel
#    state: installed
#  #with_items: nodejs,npm

- name: Downloading nvm
  shell: 'curl -L https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh > nvm_install.sh'

- name: Installing nvm
  command: bash nvm_install.sh

- name: Executing nvm
  command: bash /home/ec2-user/.nvm/nvm.sh

- name: Installing node and npm
  command: nvm install node
